### ISSUE TITLE
TensorRT model import error

### ISSUE THREAD

**Issue by mahendraBabuHari** [NathanUA/BASNet#17]
Am trying to use TensorRT to speed up the inference. I converted my model trained from scratch to ONNX to feed to TensorRT. But TensorRT is throwing this error while parsing the model,

While parsing node number 186 [Gather]:
ERROR: onnx2trt_utils.hpp:277 In function convert_axis:
[8] Assertion failed: axis >= 0 && axis < nbDims
[E] Unable to parse ONNX model file: ../data/int8_api/basnet.onnx

Any pointers on how to address this?

Thanks.

**Comment by KanchanIIT** [comment]
Hi @mahendraBabuHari, did you trained the model from scratch in ONNX or converted the trained model in PyTorch to ONNX?

**Comment by NathanUA** [comment]
Sorry， We didn’t try that way.

**Comment by mahendraBabuHari** [comment]
> Hi @mahendraBabuHari, did you trained the model from scratch in ONNX or converted the trained model in PyTorch to ONNX?

Converted the trained model in PyTorch to ONNX.

**Comment by HaoTang1** [comment]
@mahendraBabuHari  Were you able to get basnet working in TensorRT? If so can you explain the steps you took?

I'm trying to do the same but can't find any example of salient object detection in TensorRT.

Thanks.
