### ISSUE TITLE
iou loss question

### ISSUE THREAD

**Issue by pp00704831** [NathanUA/BASNet#29]
Hello, I want to ask some questions about iou loss and ssim loss. 
When I saw the code basnet_train.py, I found that : 

ssim_out = 1 - ssim_loss(pred,target)
iou_out = iou_loss(pred,target)

I think that iou loss still need to be subtracted by 1 like that:
iou_out = 1 - iou_loss(pred,target)

But why it do not need to do that?
Thanks you!

**Comment by NathanUA** [comment]
Thank you for your interests. Because the iou was defined as 1-iou in its definition part. The reason we use ssim loss as 1-Ssim is that the ssim code was borrowed from another implementation as shown in the readme. We don’t want to change its original definition so that use 1-ssim.
