### ISSUE TITLE
training with batch size =1 has too low performance

### ISSUE THREAD

**Issue by vince2003** [NathanUA/BASNet#42]
Hi Xuebin Qin,
Thank you for your great work. However, I have a problem. When I train your model with batch size =1, it has too low performance that is far from batch size=8. How to train with bach size=1 and still have good performance?
Thank you

**Comment by NathanUA** [comment]
Thanks for your interest. Yes, the batch size does matter in the training process. I think you can try to use different normalization methods, e.g. group norm, instance norm or layer norm, which doesn’t require large batch size. They may or may not help.

**Comment by vince2003** [comment]
Thank you for your reply. My advice is really effective. Performance has improved significantly.
