### ISSUE TITLE
The result of retraining

### ISSUE THREAD

**Issue by xiaobao886** [NathanUA/BASNet#61]
I tried to perform offline data enhancement according to the training method in the paper, to double the dataset of DUTS  by horizontally flipping it. Use iterative 400K weights for testing and evaluation.   MAE=0.67, But 0.47 in the paper，maxF and relaxF higher than in the paper.  Excuse me, why is this？

**Comment by xuebinqin** [comment]
Replied the similar question in https://github.com/xuebinqin/U-2-Net/issues/240.
